---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  h2:
    console.enabled: true
  console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

server:
  address: 0.0.0.0